name: cashir_quiz
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cool_alert: 1.1.0
  cupertino_icons: ^1.0.2
  get: 4.6.1
  get_storage: 2.0.3
  http: 0.13.4 
  intl: 0.17.0
  salomon_bottom_bar: 3.2.0  
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_launcher_icons: "^0.9.2"
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test: 
    sdk: flutter


flutter_icons:
  android: true
  ios: true
  image_path: "assets/cashir.jpg"

flutter: 
  uses-material-design: true

  assets:
    - assets/
    - assets/flare/

